### ISSUE TITLE
An IO Exception was thrown on generating a package

### ISSUE THREAD

**Issue by caphosra** [capra314cabra/plpm#2]
When I ran the command "plpm create", it was thrown :
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\[My User]\AppData\Roaming\PrivateLocatedPackageManager\Some.plpmpkg'.at
at ............
at System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName)
at PrivateLocatedPackageManager.PackageCreater.Build(PackageProps pkg) in C:\pathtosrc\plpmsys\PackageCreater.cs:line 58
at ............
```

**Comment by caphosra** [comment]
I'll fix it.
